modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Sinytra/ConnectorExtras/issues"

[[mods]]
modId="connectorextras_architectury_bridge"
version="${file.jarVersion}"
displayName="Connector Architectury Bridge"
authors="Su5eD"
displayURL="https://github.com/Sinytra/ConnectorExtras"
description='''
Bridges Architectury API for Fabric mods on Forge
'''
displayTest = 'IGNORE_ALL_VERSION'
[[dependencies.connectorextras_architectury_bridge]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.connectorextras_architectury_bridge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.connectorextras_architectury_bridge]]
    modId="connectormod"
    mandatory=true
    versionRange="[1.0.0-beta.18, )"
    ordering="NONE"
    side="BOTH"
