modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Sinytra/ConnectorExtras/issues"

[[mods]]
modId="connectorextras"
version="${file.jarVersion}"
displayName="Connector Extras"
authors="Su5eD"
displayURL="https://github.com/Sinytra/ConnectorExtras"
description='''

'''
[[dependencies.connectorextras]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.connectorextras]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
