modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Sinytra/ConnectorExtras/issues"

[[mods]]
modId="connectorextras_geckolib_fabric_compat"
version="${file.jarVersion}"
displayName="Connector Extras Geckolib-Fabric Compat"
authors="Su5eD"
displayURL="https://github.com/Sinytra/ConnectorExtras"
description='''
Provides forge features for geckolib fabric, which is often required by fabric mods due to containing extra classes. 
'''
displayTest = 'IGNORE_ALL_VERSION'
[[dependencies.connectorextras_geckolib_fabric_compat]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.connectorextras_geckolib_fabric_compat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.connectorextras_geckolib_fabric_compat]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.2,)"
    ordering="NONE"
    side="BOTH"
